### ISSUE TITLE
Não é bem um Issue... checkar resultados

### ISSUE THREAD

**Issue by talvasconcelos** [efernandesng/placard-api#4]
Boas, onde poderei ver os resultados dos jogos/entradas ? Numa primeira instância temos os odds e gostaria depois de saber o resultado. É possível?

Obrigado,
Tiago

**Comment by efernandesng** [comment]
Olá Tiago! Os WebServices dos JogosSantaCasa apenas disponibilizam informação sobre as odds e por isso para obteres os resultados, é necessário usar outro serviço.

**Comment by bonucci** [comment]
Olá @efernandesng , onde arranjaste a apikey?

**Comment by efernandesng** [comment]
Olá @bonucci,
Analisando o tráfego da app para Android.

**Comment by bonucci** [comment]
Obrigado Emanuel
